version: 2
updates:
  # Check for updates of crates and actions every month.  We don't check Rust
  # dependencies, because this creates way to many pull requests for trivial
  # updates, and cargo update exists.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
