[package]
name = "home"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
publish = false

[dependencies]
ureq = { version = "^2.0", features = ["tls", "native-certs"] }
toml = "^0.5"
serde = { version = "^1.0", features = ["derive"] }
dirs = "^3.0"
anyhow = "^1.0"