[package]
name = "home"
description = "Commute homewards"
version = "1.0.0"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
homepage = "https://github.com/swsnr/mvg_home"
repository = "https://github.com/swsnr/mvg_home.git"
edition = "2021"
publish = false

[dependencies]
toml = "0.5.10"
serde = { version = "1.0.152", features = ["derive"] }
dirs = "4.0.0"
anyhow = "1.0.68"
reqwest = { version = "0.11.13", features = ["json"] }
url = "2.3.1"
time = { version = "0.3.17", features = [
    "local-offset",
    "macros",
    "formatting",
    "serde",
] }
clap = { version = "4.0.32", features = ["derive"] }
futures = "0.3.25"
flexbuffers = "2.0.0"
tracing = "0.1.37"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
glib = { version = "0.16.7", features = ["log"] }
system_proxy = "0.1.3"
tokio = { version = "1.23.0", features = ["rt"] }
humantime = "2.1.0"
