[[connections]]
start = "Hauptbahnhof"
destination = "Ostbahnhof München"
walk_to_start = "10min"

[[connections]]
start = "Karlsplatz (Stachus)"
destination = "Ostbahnhof München"
walk_to_start = "5min"
