[[connections]]
start = "Hauptbahnhof"
destination = "Ostbahnhof München"
walk_to_start = "10min"
ignore_starting_with = ["U5"]

[[connections]]
start = "Waldfriedhof"
destination = "Schwanthaler Höhe"
walk_to_start = "5min"
